version: "3.8"

services:
  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: voiceid
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build: ./services/api
    environment:
      DB_URL_ASYNC: "postgresql+asyncpg://postgres:${POSTGRES_PASSWORD}@db/voiceid"
      RABBIT_URL: "amqp://guest:guest@rabbit//"
      API_KEY: "${API_KEY}"
    depends_on:
      - db
      - rabbit
    ports:
      - "8000:8000"
    command: uvicorn app:app --host 0.0.0.0 --reload

  worker:
    build: ./services/worker
    environment:
      DB_URL_SYNC: "postgresql+psycopg://postgres:${POSTGRES_PASSWORD}@db/voiceid"
      RABBIT_URL: "amqp://guest:guest@rabbit//"
    depends_on:
      - db
      - rabbit
    command: celery -A tasks worker -l info

volumes:
  pgdata:
