"""create embeddings table

Revision ID: bab026549a4b
Revises: 
Create Date: 2025-05-13 16:31:11.719631

"""
from typing import Sequence, Union
import pgvector.sqlalchemy 
from pgvector.sqlalchemy import Vector     # ← добавьте
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bab026549a4b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.VARCHAR(length=64), nullable=False),
    sa.Column('speaker_id', sa.String(), nullable=False),
    sa.Column('vec', Vector(dim=192), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embeddings_speaker_id'), 'embeddings', ['speaker_id'], unique=False)
    op.create_index(op.f('ix_embeddings_user'), 'embeddings', ['user'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embeddings_user'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_speaker_id'), table_name='embeddings')
    op.drop_table('embeddings')
    # ### end Alembic commands ###
